name: Auto Release Tag

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create tags/releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "v1.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Increment patch version
        id: bump_version
        run: |
          tag=${{ steps.get_tag.outputs.latest_tag }}
          # Extract numbers
          IFS='.' read -r -a parts <<< "${tag#v}"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}
          patch=$((patch + 1))
          new_tag="v$major.$minor.$patch"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create new tag
        run: |
          git config user.name "GKG Bot"
          git config user.email "gkg-bot@users.noreply.github.com"

          if [[ "${GITHUB_REF#refs/heads/}" == "develop" ]]; then
            tag="${{ steps.bump_version.outputs.new_tag }}-beta"
          else
            tag="${{ steps.bump_version.outputs.new_tag }}"
          fi

          git tag "$tag"
          git push origin "$tag"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          prerelease: ${{ github.ref == 'refs/heads/develop' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}