name: Go Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.24.1
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build ./...

      - name: Run tests with coverage
        run: |
          go test -v -coverpkg=./... -coverprofile=coverage.out $(go list ./... | grep -v '/internal/stress') -covermode=atomic
          go tool cover -func=coverage.out
          go tool cover -html=coverage.out -o coverage.html

      - name: Commit coverage files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GKG Bot — Go Kafka Genius"
          git config user.email "gkg-bot@users.noreply.github.com"
          git add coverage.out coverage.html
          git diff --quiet && git diff --staged --quiet || git commit -m "ci: update coverage reports"
          git push origin HEAD:${{ github.ref }}